name: Go

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DEPLOY: ${{ github.ref == 'refs/heads/master' }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v ./...

#    - name: Generate Cases 
#      if: ${{ env.DEPLOY }}
#      run: ./geonet cases
#
#    - name: Publish Cases to GH Pages
#      if: ${{ env.DEPLOY }}
#      uses: JamesIves/github-pages-deploy-action@v4
#      with:
#        folder: public # The folder the action should deploy.
