name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v ./...

    - name: Generate Cases 
      run: ./geonet cases

    - name: Publish Cases to GH Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public # The folder the action should deploy.
